name: Deploy Deno App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Cache Deno dependencies
        id: cache-deno-deps
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/deno
          key: ${{ runner.os }}-deno-${{ hashFiles('**/*.ts') }}
          restore-keys: |
            ${{ runner.os }}-deno-

      - name: Run the Deno application
        run: |
          deno run --allow-net --allow-read --allow-write app.ts
